Improve running instruction
philectron/lil-lisp pull request #7
Opened 2020-03-10 06:04 UTC by khashf

2020-03-10 07:16 UTC, philectron requested changes
Be a bit more forrmal and technical and be sure to spell-check and grammar-check the README. Everything else LGTM!

2020-03-10 07:16 UTC, philectron commented on README.md
> +An example, let say we'd like to test the interperter on the following Lil' Lisp program
> An example, **let say** we'd like to test the **interperter** on the following Lil' Lisp program

~~Vibe~~ Spell check!

Change `An example` too `For example`, `let say` to `let's say`, `interperter` to `interpreter`

2020-03-10 07:16 UTC, philectron commented on README.md
> +This will output the detailed content of tests, along with our descriptions of the tests, the expected outputs, and the outputs. The whole output is paged with `less` pager for convenience
Add a period at the end.

2020-03-10 07:16 UTC, philectron commented on README.md
> +This Lil' Lisp program define a function named `ais3` that return whether its first argument `a` is equal to integer `3` or not. Then, this program call that same function with the first argument is
> This Lil' Lisp program **defines** a function named `ais3` that **returns**

> Then, this program **calls** that same function with the first argument ~~is~~ `3`

> ~~Obviously,~~ The final output should be `True`.

2020-03-10 07:16 UTC, philectron commented on README.md
> +So, the manual test should be (assuming you already loaded the `Main` module):
> ~~So,~~ The manual test should be

2020-03-10 07:16 UTC, philectron commented on README.md
> +- We tested three features of the interpreter at the same time: Function (`Func` and `Call`), binding (`Ref`), and boolean operation (`BoolExprBi`)
Add a period at the end.

2020-03-10 07:16 UTC, philectron commented on README.md
> +- The output is `B True`, which is what we expected. So the interpreter has worked correctly.
> ~~So~~ The interpreter has worked correctly.

2020-03-10 08:39 UTC, khashf commented
@philectron Thanks for the review. Next time use the [change suggestion](https://haacked.com/archive/2019/06/03/suggested-changes/) feature for convenience.

2020-03-11 19:19 UTC, philectron approved these changes

2020-03-11 19:19 UTC, merged